name: "publish npm"

on: push

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: node
              run: npm run build
            - name: publish
              run: npm publish --access public
              working-directory: my-package
              env:
                  NODE_AUTH_TOKEN: ${{VUE3_VITE_TYPESCRIPT_LIB_SAMPLE_NPMJS_TOKEN}}
